### ISSUE TITLE
Codeium doesn't work at all if project is on WSL

### ISSUE THREAD

**Issue by pvradu** [Exafunction/codeium-sublime#13]
On top of the issues described here: https://github.com/Exafunction/codeium-sublime/issues/1, I just discovered Codeium will not load any suggestions if project is hosted on WSL. Here's the error from the console:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 963, in on_modified_async
    run_view_callbacks('on_modified_async', view_id)
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 741, in run_view_callbacks
    callback(v, *args)
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 202, in exception_handler
    return event_handler(*args)
  File "C:\Users\user\AppData\Roaming\Sublime Text\Installed Packages\Codeium.sublime-package\display_completions.py", line 89, in on_modified_async
    self.req = GetCompletionsRequest(view)
  File "C:\Users\user\AppData\Roaming\Sublime Text\Installed Packages\Codeium.sublime-package\protorequests.py", line 56, in __init__
    self.make_document(buf.document)
  File "C:\Users\user\AppData\Roaming\Sublime Text\Installed Packages\Codeium.sublime-package\protorequests.py", line 80, in make_document
    doc.relative_path = os.path.relpath(doc.absolute_path)
  File "./python3.8/ntpath.py", line 703, in relpath
ValueError: path is on mount '\\\\wsl.localhost\\Ubuntu-22.04', start on mount 'C:
```

**Comment by pbosakov** [comment]
Looks related to https://github.com/Exafunction/codeium-sublime/issues/7
