### ISSUE TITLE
ValueError: path is on mount 'D:', start on mount 'C:'

### ISSUE THREAD

**Issue by pbosakov** [Exafunction/codeium-sublime#7]
This apparently happens when trying to autocomplete code on a mount that's different from the drive where Sublime Text is installed.

```
ValueError: path is on mount 'D:', start on mount 'C:'
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\Lib\python38\sublime_plugin.py", line 963, in on_modified_async
    run_view_callbacks('on_modified_async', view_id)
  File "C:\Program Files\Sublime Text 3\Lib\python38\sublime_plugin.py", line 741, in run_view_callbacks
    callback(v, *args)
  File "C:\Program Files\Sublime Text 3\Lib\python38\sublime_plugin.py", line 202, in exception_handler
    return event_handler(*args)
  File "C:\Users\Petko\AppData\Roaming\Sublime Text 3\Installed Packages\Codeium.sublime-package\display_completions.py", line 89, in on_modified_async
    self.req = GetCompletionsRequest(view)
  File "C:\Users\Petko\AppData\Roaming\Sublime Text 3\Installed Packages\Codeium.sublime-package\protorequests.py", line 56, in __init__
    self.make_document(buf.document)
  File "C:\Users\Petko\AppData\Roaming\Sublime Text 3\Installed Packages\Codeium.sublime-package\protorequests.py", line 80, in make_document
    doc.relative_path = os.path.relpath(doc.absolute_path)
  File "./python3.8/ntpath.py", line 703, in relpath
`

**Comment by kkzhang** [comment]
same
